version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - '5555:80'
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: simpleuser
            WORDPRESS_DB_PASSWORD: simplepass
            WORDPRESS_DB_NAME: simpledb
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: simpleuser
            MYSQL_PASSWORD: simplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
        # TO USE A DUMP OF DB IN THE SAME PROJECT DIRECTORY
            - ./exampledb.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1